title: Maggie's blog
email: cv098150@gmail.com
description: "Maggie's devlopment blog"
baseurl: "/blog"
url: "https://cv098150.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: cv098150

# Build settings
theme: minima
plugins:
  - jekyll-feed